// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import pigeon.FlutterError

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
            exception.code,
            exception.message,
            exception.details
    )
  } else {
    listOf(
            exception.javaClass.simpleName,
            exception.toString(),
            "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AlarmAPI {
  fun setupBudgetReset(budgetId: Long, firstTriggerDate: String, period: String)

  companion object {
    /** The codec used by AlarmAPI. */
    private val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `AlarmAPI` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: AlarmAPI?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.AlarmAPI.setupBudgetReset", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val budgetIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val firstTriggerDateArg = args[1] as String
            val periodArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.setupBudgetReset(budgetIdArg, firstTriggerDateArg, periodArg)
              listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
